[package]
name = "sov-modules-api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
sov-state = { workspace = true }
sovereign-sdk = { workspace = true }
borsh = { workspace = true}
thiserror = { workspace = true }
sovereign-db = { workspace = true }
first-read-last-write-cache = { workspace = true }

[features]
mocks = []
