[package]
name = "sov-modules-api"
version = "0.1.0"
edition = "2021"

[dependencies]
sov-state = { workspace = true }
sovereign-sdk = { workspace = true }
borsh = { workspace = true, optional = true}

[features]
mocks = ["dep:borsh"]
