[package]
name = "sov-modules-impl"
version = "0.1.0"
edition = "2021"

[dependencies]
sov-modules-api = { workspace = true }
sov-modules-macros = { workspace = true }
sov-state = { workspace = true }
sovereign-sdk = { workspace = true }

