[package]
name = "sov-state"
version = "0.1.0"
edition = "2021"

[dependencies]
sovereign-sdk = { workspace = true }
first-read-last-write-cache = { workspace = true }
jellyfish-merkle-generic = { workspace = true }

