[package]
name = "sov-modules-macros"
version = "0.1.0"
edition = "2021"
autotests = false

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/all_tests.rs"

[dev-dependencies]
trybuild = "1.0"
sov-modules-api = { workspace = true ,  features = ["mocks"]}
sov-state = {workspace = true}

[dependencies]
sov-modules-api = { workspace = true }

syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
borsh = { workspace = true }
