name: Rust

on:
  push:
    branches: ["research"]
  pull_request:
    branches: ["research"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2.2.0
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: Swatinem/rust-cache@v2.2.0
        - name: Run cargo test
          uses: actions-rs/cargo@v1
          with:
            command: test